# Generated by Django 5.2.5 on 2025-10-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.home')),
            ],
        ),
    ]
