# Generated by Django 5.2.5 on 2025-10-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_alternatehome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternatehome',
            old_name='rel',
            new_name='href_lang',
        ),
    ]
