# Generated by Django 5.2.5 on 2025-10-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_rename_rel_alternatehome_href_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'heading']},
        ),
        migrations.AlterModelOptions(
            name='servicevariant',
            options={'ordering': ['order', 'heading']},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.service'),
        ),
    ]
