# Generated by Django 5.2.5 on 2025-08-13 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='external_links',
            field=models.TextField(blank=True, help_text='List of external links with descriptions (one per line)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='internal_links',
            field=models.TextField(blank=True, help_text='List of internal links to other blog posts (one per line)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='metrics',
            field=models.TextField(blank=True, help_text='List of key metrics and results (one per line)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technologies_used',
            field=models.TextField(blank=True, help_text='List of technologies used (one per line)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True, help_text='List of benefits (one per line)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='List of service features (one per line)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='process_steps',
            field=models.TextField(blank=True, help_text='List of process steps (one per line)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='achievements',
            field=models.TextField(blank=True, help_text='Professional achievements and awards (one per line)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of professional certifications (one per line)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='education',
            field=models.TextField(blank=True, help_text='Educational background (one per line)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='expertise',
            field=models.TextField(blank=True, help_text='List of areas of expertise (one per line)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='speaking_engagements',
            field=models.TextField(blank=True, help_text='Speaking engagements and presentations (one per line)'),
        ),
    ]
