# Generated by Django 5.2.5 on 2025-08-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blogcategory_created_at_blogcategory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Portfolio Categories'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='schema_markup',
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PortfolioMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.CharField(help_text='The metric value (e.g., 300%, $2.1M, 2.5x)', max_length=100)),
                ('metric_label', models.CharField(help_text='Description of the metric (e.g., Traffic Increase, Revenue Generated)', max_length=200)),
                ('metric_type', models.CharField(choices=[('percentage', 'Percentage'), ('currency', 'Currency'), ('multiplier', 'Multiplier'), ('number', 'Number'), ('text', 'Text')], default='text', help_text='Type of metric for proper formatting', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_items', to='website.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Metric',
                'verbose_name_plural': 'Portfolio Metrics',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
