# Generated by Django 5.2.5 on 2025-08-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_portfoliocategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='project_duration',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='technologies_used',
        ),
    ]
