# Generated by Django 5.2.5 on 2025-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_portfolio_project_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='schema_markup',
            field=models.JSONField(blank=True, default=dict, help_text='Custom JSON-LD schema markup', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='schema_markup',
            field=models.JSONField(blank=True, default=dict, help_text='Custom JSON-LD schema markup', null=True),
        ),
    ]
